version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5859:5859"
    links:
      - mongo
      - elk
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev
  mongo:
    image: mongo
    volumes:
      - datavolume:/data/db
    ports:
      - "27017:27017"
  elk:
    image: sebp/elk
    ports:
      - "5601:5601" # Kibana
      - "9200:9200" # Elastic search
      - "5044:5044" # Logstash - filebeat port
      - "10514:10514" # Logstash - tcp port
    volumes:
      - elk-data:/var/lib/elasticsearch
      - ./elk-input.conf:/etc/logstash/conf.d/03-tcp-input.conf
      - ./elk-output.conf:/etc/logstash/conf.d/30-output.conf
volumes:
  datavolume: {}
  node_modules: {}
  elk-data: {}